version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes

  idempotency_pg:
    image: postgres:latest
    container_name: idempotency_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: idempotency
      POSTGRES_USER: idempotency
      POSTGRES_PASSWORD: idempotency
    ports:
      - "5430:5432"
  redis:
    image: redis:latest
    ports:
      - "6370:6379"
