spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/idempotency
    username: idempotency
    password: idempotency
    driver-class-name: org.postgresql.Driver
    hikari:
      validation-timeout: 260
      minimum-idle: 0
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092